#!/bin/sh

config=/etc/sshtunnel.conf
socket=/tmp/ssh_tunnel_sck

[ ! -f $config ] && echo "No config file found in $config"

. $config

sshcmd() {
/usr/bin/ssh \
-o "ControlPath=$socket" \
-o "ControlMaster=auto" \
-o "ControlPersist=5m" \
-o "ServerAliveInterval=10" \
-o "ServerAliveCountMax=12" \
-o "IdentitiesOnly=yes" \
-i "$IDENTITY_FILE" \
$1 \
"$REMOTE_HOST" \
"$2"
}

local_cmd() {
    $1
    log "  local: $1"
}

remote_cmd() {
    sshcmd "--" "$1"
    log " remote: $1"
}

log() {
    echo "$1"
}

socketStatus() {
    ssh -O check -S $socket $REMOTE_HOST 2> /dev/null
}

start() {
    if socketStatus; then
        echo "Seems already running"
        return 0
    fi

    sshcmd "-w $LOCAL_TUN:$REMOTE_TUN -T" exit > /dev/null
    [ $? -ne 0 ] && echo "Something is wrong" && exit 2

    log "Running ssh tunnel session $socket."

    while true; do
        ip link show tun${LOCAL_TUN} > /dev/null
        if [ $? -eq 0 ]; then
            break
        fi
        echo "Waiting for local adapter tun${LOCAL_TUN}"
        sleep 1
    done

    while true; do
        sshcmd " " "ip link show tun${REMOTE_TUN}" > /dev/null
        if [ $? -eq 0 ]; then
            break
        fi
        echo "Waiting for remote adapter tun${REMOTE_TUN}"
        sleep 1
    done

    local_cmd "ifconfig tun$LOCAL_TUN $LOCAL_IP pointopoint $REMOTE_IP netmask $NETMASK"
    remote_cmd "ifconfig tun$REMOTE_TUN $REMOTE_IP pointopoint $LOCAL_IP netmask $NETMASK"

    for r in $LOCAL_ROUTES; do
        local_cmd "ip route add $r dev tun$LOCAL_TUN"
    done
}

stop() {
    if socketStatus; then
        ssh -O exit -S $socket $REMOTE_HOST
    else
        echo "Should be stopped already"
    fi
}

status() {
    socketStatus
    if [ $? -ne 0 ]; then
        echo "Not running"
    else
        echo "Tunnel is running"
    fi
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "$0 [start|stop|restart|status]"
        ;;
esac
